FROM node:14.2

COPY package-lock.json .
COPY package.json .
RUN npm install -g ts-node
RUN npm install 

ADD build ./build
ADD lib ./lib
ADD routes ./routes
COPY global.ts .
COPY index.ts .

CMD ts-node index.ts