FROM node:14.2

COPY package-lock.json .
COPY package.json .
RUN npm install -g ts-node
RUN npm install 

COPY global.ts .
COPY index.ts .

ADD routes ./routes
ADD spotify ./spotify
ADD socketio ./socketio
ADD build ./build

CMD ts-node index.ts